Resolve Workspace is namespace error
CSharpVirtualDocumentPublisher.cs(149,78): error CS0118: 'Workspace' is a namespace but is used like a type [\src\Razor\src\Microsoft.VisualStudio.LanguageServerClient.Razor\Microsoft.VisualStudi
o.LanguageServerClient.Razor.csproj]
CSharpVirtualDocumentPublisher.cs(128,34): error CS0534: 'CSharpVirtualDocumentPublisher.CSharpVirtualDocumentContainer.SourceTextLoader' does not implement inherited abstract member 'TextLoader.LoadTextAndVersionAsync(Workspace, Docu
mentId, CancellationToken)' [\src\Razor\src\Microsoft.VisualStudio.LanguageServerClient.Razor\Microsoft.VisualStudio.LanguageServerClient.Razor.csproj]